name: Sync template
on: push

jobs:
  update-template-branch:
    name: Update branch from template repository
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Update template branch
      run: |
        git remote add template_repo https://github.com/antfu/starter-vscode.git
        git pull template_repo main:template
        git push origin template