# File: .github/workflows/template-sync.yml

on:
  # cronjob trigger
  push:
  # manual trigger
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest

    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: update template branch
        run: |
          git remote add template_repo https://github.com/xia0hj/test-template.git
          git pull template_repo main:template --ff-only
          git push origin template